# Generated by Django 3.2.8 on 2021-11-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211108_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersiteproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
