# Generated by Django 3.2.8 on 2021-11-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_orderingproduct_track_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldsiteproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='soldsiteproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderSiteProduct',
        ),
        migrations.DeleteModel(
            name='SoldSiteProduct',
        ),
    ]
