# Generated by Django 3.2.8 on 2022-01-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_soldproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(help_text='Id пользователя телеграм', unique=True),
        ),
    ]
