# Generated by Django 3.2.8 on 2021-10-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Закупочная цена товара', max_digits=10),
            preserve_default=False,
        ),
    ]
