# Generated by Django 3.2.8 on 2021-10-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0002_offlineproduct_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineReceptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Заметка приемки', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Закупочная цена', max_digits=10)),
                ('count', models.IntegerField(help_text='Кол-во товара в приемке')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата и время приемки')),
                ('liquidated', models.BooleanField(default=False, help_text='Ликвидация товара')),
                ('product', models.ForeignKey(help_text='Товар', on_delete=django.db.models.deletion.CASCADE, to='seller_site.offlineproduct')),
            ],
        ),
    ]
