# Generated by Django 3.2.8 on 2021-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0005_offlinesoldproduct_orderingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinecategory',
            name='price_for_seller',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Сумма отчисления для продавца', max_digits=10),
            preserve_default=False,
        ),
    ]
