# Generated by Django 3.2.8 on 2021-10-24 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_site', '0006_offlinecategory_price_for_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderingProduct',
            new_name='OfflineOrderingProduct',
        ),
    ]
