# Generated by Django 3.2.8 on 2021-10-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0007_rename_orderingproduct_offlineorderingproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinesoldproduct',
            name='user',
        ),
    ]
