# Generated by Django 3.2.8 on 2021-10-31 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0013_offlinesoldproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineorderingproduct',
            name='sold_product',
        ),
        migrations.AddField(
            model_name='offlinesoldproduct',
            name='order',
            field=models.ForeignKey(default=1, help_text='Заказ', on_delete=django.db.models.deletion.CASCADE, to='seller_site.offlineorderingproduct'),
            preserve_default=False,
        ),
    ]
