# Generated by Django 3.2.8 on 2021-11-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0014_auto_20211031_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinereceptionproduct',
            name='hui',
            field=models.BooleanField(default=False, help_text='Ликвидация товара'),
        ),
    ]
