# Generated by Django 3.2.8 on 2022-01-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0015_offlinereceptionproduct_hui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinereceptionproduct',
            name='hui',
        ),
        migrations.AlterField(
            model_name='offlinesoldproduct',
            name='order',
            field=models.ForeignKey(help_text='Заказ', on_delete=django.db.models.deletion.CASCADE, related_name='offlinesoldproduct', to='seller_site.offlineorderingproduct'),
        ),
    ]
