# Generated by Django 3.2.8 on 2021-11-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0015_offlinereceptionproduct_hui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinereceptionproduct',
            name='hui',
        ),
    ]
