# Generated by Django 3.2.8 on 2021-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_alter_ordersiteproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersiteproduct',
            name='track_code',
            field=models.CharField(blank=True, help_text='Трек-код заказа', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soldsiteproduct',
            name='order',
            field=models.ForeignKey(help_text='Заказ', on_delete=django.db.models.deletion.CASCADE, related_name='soldproduct', to='online_shop.ordersiteproduct'),
        ),
    ]
