# Generated by Django 3.2.8 on 2021-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0007_ordersiteproduct_pay_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersiteproduct',
            name='pay_url',
            field=models.URLField(blank=True, help_text='Url оплаты в QIWI', max_length=250, null=True),
        ),
    ]
