# Generated by Django 3.2.5 on 2021-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=245, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
