# Generated by Django 3.2.8 on 2021-11-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211106_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingproduct',
            name='site_bool',
            field=models.BooleanField(default=False),
        ),
    ]
