# Generated by Django 3.2.8 on 2021-11-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_orderingproduct_site_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingproduct',
            name='site_bool',
        ),
        migrations.CreateModel(
            name='OrderSiteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('track_code', models.BigIntegerField(blank=True, help_text='Трек-код заказа', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sold_product', models.ManyToManyField(help_text='Товары в заказе', to='main_app.SoldProduct')),
            ],
        ),
    ]
