# Generated by Django 3.2.8 on 2021-11-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211107_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersiteproduct',
            name='sold_product',
        ),
        migrations.CreateModel(
            name='SoldSiteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена на момент продажи', max_digits=10)),
                ('count', models.IntegerField(help_text='Кол-во проданного товара')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата и время продажи')),
                ('order', models.ForeignKey(help_text='Заказ', on_delete=django.db.models.deletion.CASCADE, to='main_app.ordersiteproduct')),
                ('product', models.ForeignKey(help_text='Продукт', on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
    ]
