# Generated by Django 3.2.5 on 2021-10-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_soldproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionproduct',
            old_name='purchase_price',
            new_name='price',
        ),
    ]
