# Generated by Django 3.2.5 on 2021-10-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_purchase_price_receptionproduct_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoldProduct',
            new_name='ReceptionSoldProduct',
        ),
        migrations.DeleteModel(
            name='ReceptionProduct',
        ),
    ]
