# Generated by Django 3.2.5 on 2021-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211002_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionsoldproduct',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
