# Generated by Django 3.2.8 on 2021-11-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_category_pk_for_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pk_for_telegram',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='pk_for_telegram',
        ),
    ]
