# Generated by Django 3.2.5 on 2021-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20211002_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionproduct',
            name='liquidated',
            field=models.BooleanField(default=True),
        ),
    ]
