# Generated by Django 3.2.8 on 2021-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211114_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingproduct',
            name='track_code',
            field=models.CharField(blank=True, help_text='Трек-код заказа', max_length=150, null=True),
        ),
    ]
