# Generated by Django 3.2.5 on 2021-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_telegramproductcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramproductcounter',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
