# Generated by Django 3.2.8 on 2021-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_orderingproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='order',
            field=models.ForeignKey(help_text='Заказ', on_delete=django.db.models.deletion.CASCADE, related_name='soldproduct', to='main_app.orderingproduct'),
        ),
    ]
