# Generated by Django 3.2.5 on 2021-10-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_telegramproductcounter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProductCartCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('counter', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.telegramuser')),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramProductCounter',
        ),
    ]
