# Generated by Django 3.2.5 on 2021-10-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20211003_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_count_product',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
