# Generated by Django 3.2.5 on 2021-10-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_category_max_count_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
