# Generated by Django 3.2.7 on 2021-10-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20211004_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_comment', models.CharField(max_length=255)),
                ('delivery_pay', models.IntegerField()),
                ('cart', models.ManyToManyField(to='main_app.TelegramProductCartCounter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.telegramuser')),
            ],
        ),
    ]
