# Generated by Django 3.2.7 on 2021-10-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_payproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payproduct',
            name='cart',
        ),
    ]
