# Generated by Django 3.2.7 on 2021-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_payproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='payproduct',
            name='product_pay',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
