# Generated by Django 3.2.7 on 2021-10-04 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_payproduct_product_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payproduct',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
