# Generated by Django 3.2.7 on 2021-10-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_payproduct_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='check_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='track_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.telegramuser'),
            preserve_default=False,
        ),
    ]
