# Generated by Django 3.2.7 on 2021-10-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20211005_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='delivery_pay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
