# Generated by Django 3.2.7 on 2021-10-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_soldproduct_delivery_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='check_admin',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='delivery_pay',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='track_code',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='user',
        ),
        migrations.CreateModel(
            name='OrderingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_pay', models.IntegerField()),
                ('track_code', models.IntegerField(blank=True, null=True)),
                ('check_admin', models.BooleanField(default=False)),
                ('sold_product', models.ManyToManyField(to='main_app.SoldProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.telegramuser')),
            ],
        ),
    ]
