# Generated by Django 3.2.7 on 2021-10-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20211005_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
    ]
