# Generated by Django 3.2.7 on 2021-10-06 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_soldproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingproduct',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
