# Generated by Django 3.2.7 on 2021-10-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_orderingproduct_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingproduct',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderingproduct',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderingproduct',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderingproduct',
            name='post_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
