# Generated by Django 3.2.7 on 2021-10-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_telegramuser_search_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='QiwiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
