# Generated by Django 3.2.7 on 2021-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_qiwitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiwitoken',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
