# Generated by Django 3.2.7 on 2021-10-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_qiwitoken_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingproduct',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderingproduct',
            name='post_index',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderingproduct',
            name='track_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qiwitoken',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
