# Generated by Django 3.2.8 on 2021-10-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20211009_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_pay', models.IntegerField()),
                ('track_code', models.BigIntegerField(blank=True, null=True)),
                ('payment_bool', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('fio', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('post_index', models.BigIntegerField(blank=True, null=True)),
                ('order_product', models.ManyToManyField(to='main_app.ProductInCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.telegramuser')),
            ],
        ),
    ]
