# Generated by Django 3.2.8 on 2021-10-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_orderincard_productincard'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingproduct',
            name='payment_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='payment_bool',
            field=models.BooleanField(default=False),
        ),
    ]
