# Generated by Django 3.2.8 on 2021-10-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_auto_20211014_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldproduct',
            old_name='date',
            new_name='datetime',
        ),
    ]
