# Generated by Django 3.2.8 on 2021-10-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_rename_date_soldproduct_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldproduct',
            old_name='datetime',
            new_name='date',
        ),
    ]
