# Generated by Django 3.2.7 on 2021-10-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_rename_datetime_soldproduct_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincard',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderInCard',
        ),
        migrations.DeleteModel(
            name='ProductInCard',
        ),
    ]
