# Generated by Django 3.2.8 on 2021-10-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_auto_20211022_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingproduct',
            name='qiwi_bool',
            field=models.BooleanField(default=False, help_text='Способ оплаты - киви'),
        ),
    ]
