# Generated by Django 3.2.8 on 2021-10-23 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_site', '0003_offlinereceptionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinereceptionproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
