# Generated by Django 3.2.8 on 2021-10-24 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_site', '0004_offlinereceptionproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена на момент продажи', max_digits=10)),
                ('count', models.IntegerField(help_text='Кол-во проданного товара')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата и время продажи')),
                ('product', models.ForeignKey(help_text='Продукт', on_delete=django.db.models.deletion.CASCADE, to='seller_site.offlineproduct')),
                ('user', models.ForeignKey(help_text='Продавец', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа')),
                ('sold_product', models.ManyToManyField(help_text='Товары в заказе', to='seller_site.OfflineSoldProduct')),
                ('user', models.ForeignKey(help_text='Продавец', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
