# Generated by Django 3.2.8 on 2021-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0008_remove_offlinesoldproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorderingproduct',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
