# Generated by Django 3.2.8 on 2021-10-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0009_offlineorderingproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineorderingproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
