# Generated by Django 3.2.8 on 2021-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0010_alter_offlineorderingproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesoldproduct',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
