# Generated by Django 3.2.8 on 2021-10-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0011_offlinesoldproduct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesoldproduct',
            name='price_for_seller',
            field=models.IntegerField(default=10, help_text='Отчисления продавцу'),
            preserve_default=False,
        ),
    ]
