# Generated by Django 3.2.8 on 2022-01-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_site', '0014_auto_20211031_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinesoldproduct',
            name='order',
            field=models.ForeignKey(help_text='Заказ', on_delete=django.db.models.deletion.CASCADE, related_name='offlinesoldproduct', to='seller_site.offlineorderingproduct'),
        ),
    ]
